baseURL                   = "https://ryali93.github.io/blog"
builddrafts                = false
languageCode               = "en-us"
# canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "docs"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3

theme                      = "AllinOne"
title                      = "Roy Yali"

pygmentsuseclasses         = true

[permalinks]
  blog                     = "blog/:year-:month/:slug/"

[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"

#[menu]
#  [[menu.main]]
#    name                   = "Contact me"
#    weight                 = -110
#    identifier             = "contact"
#    url                    = "contact/" 
#
#  [[menu.main]]
#    name                   = "About"
#    weight                 = -110
#    identifier             = "about"
#    url                    = "about/" 

[params]
  faviconfile              = "img/zheng.png"  
  avatar                   = "img/profile.jpg"
  author                   = "Roy Yali Samaniego"
  description              = ["GIS Developer", "Geospatial data geek", "Geographer Engineer "]  
  welcome_head             = "Bienvenido!"
  welcome_word             = "~ Comparte si te interesa"

  latestpostscount         = 5
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "ryali93@email.com"
  github                   = "//github.com/ryali93"
  linkedin                 = "//linkedin.com/in/ryali93"
  facebook                 = "//facebook.com/ryali93"
  # googleplus               = "//plus.google.com/u/0/103444698890916784040"
  twitter                  = "//twitter.com/ryali93" 
  # px500                    = "//px500"
  # instagram                = "//instagram.com/you"
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"